### ISSUE TITLE
AssertionError: Cannot create tower clone_1 under reuse=True!

### ISSUE THREAD

**Issue by huangZchao** [twangnh/Distilling-Object-Detectors-Shuffledet#3]
Traceback (most recent call last):
  File "train_multi_gpu.py", line 162, in <module>
    tf.app.run()
  File "/home/huawei/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_multi_gpu.py", line 158, in main
    train()
  File "train_multi_gpu.py", line 87, in train
    optimizer=optimizer, freeze_variable_func=freeze_variable_func)
  File "/home/huawei/PycharmProjects/Distilling-Object-Detectors-Shuffledet/lib/utils/model_deploy.py", line 350, in deploy
    clones = create_clones(config, model_fn, args)
  File "/home/huawei/PycharmProjects/Distilling-Object-Detectors-Shuffledet/lib/utils/model_deploy.py", line 191, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/huawei/PycharmProjects/Distilling-Object-Detectors-Shuffledet/lib/models/shuffleDet_sup.py", line 74, in model_fn
    self._add_forward_graph(student)
  File "/home/huawei/PycharmProjects/Distilling-Object-Detectors-Shuffledet/lib/models/shuffleDet_sup.py", line 248, in _add_forward_graph
    with TowerContext(tf.get_default_graph().get_name_scope(), is_training=mc.IS_TRAINING):
  File "/home/huawei/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorpack/tfutils/tower.py", line 245, in TowerContext
    return TrainTowerContext(tower_name, vs_name=vs_name)
  File "/home/huawei/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/tensorpack/tfutils/tower.py", line 185, in __init__
    "Cannot create tower {} under reuse=True!".format(ns_name)
AssertionError: Cannot create tower clone_1 under reuse=True!

**Comment by sara782** [comment]
Hello! Did you ever figure out the solution for this?!
